# 9 WorkFlow Analista Jr

### 9.1 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
<br>El Analista Jr corre sus scripts en la virtual manchine **desktop-jr** que tiene estas características


*   Normal, paga tarifa completa, nunca es apagada por Google
*   reside en el datacenter de Toronto, Canada
*   64 GB de memoria RAM
*   8 vCPU
*  Semillas propias Matías Odello: 159636, 264797, 357159, 753159, 456852.

## 9.3  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Jul 12 20:27:47 2026"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671142 35.9 1479544    79.1 1479544  79.1
Vcells 1242548  9.5 8388608    64.0 1978639  15.1

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:base’:

    %notin%


Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
PARAM <- list()
PARAM$semilla_primigenia <- 456852

PARAM$experimento <- 9235
PARAM$dataset <- "analistajr_competencia_2026.csv.gz"

#### Carpeta del Experimento

In [5]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("WF", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

### 9.3.1   Preprocesamiento del dataset

#### 9.3.1.1  DT incorporar dataset

In [6]:
# lectura del dataset
dataset <- fread(paste0("/content/datasets/", PARAM$dataset))

#### 9.3.1.2  CA  Catastrophe Analysis
Se intentan reparar las variables que para un mes están con todos los valores en cero.

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

In [7]:
if( !require("mice")) install.packages("mice", repos = "http://cran.us.r-project.org")
require("mice")

Loading required package: mice


Attaching package: ‘mice’


The following object is masked from ‘package:stats’:

    filter


The following objects are masked from ‘package:base’:

    cbind, rbind

In [8]:
# Escrito por alumnos de  Universidad Austral  Rosario

Corregir_MICE <- function(pcampo, pmeses) {

  meth <- rep("", ncol(dataset))
  names(meth) <- colnames(dataset)
  meth[names(meth) == pcampo] <- "sample"

  # llamada a mice  !
  imputacion <- mice(dataset,
    method = meth,
    maxit = 5,
    m = 1,
    seed = 7)

  tbl <- mice::complete(dataset)

  dataset[, paste0(pcampo) := ifelse(foto_mes %in% pmeses, tbl[, get(pcampo)], get(pcampo))]

}

In [9]:
Corregir_interpolar <- function(pcampo, pmeses) {

  tbl <- dataset[, list(
    "v1" = shift(get(pcampo), 1, type = "lag"),
    "v2" = shift(get(pcampo), 1, type = "lead")
  ),
  by = eval(envg$PARAM$dataset_metadata$entity_id)
  ]

  tbl[, paste0(envg$PARAM$dataset_metadata$entity_id) := NULL]
  tbl[, promedio := rowMeans(tbl, na.rm = TRUE)]

  dataset[
    ,
    paste0(pcampo) := ifelse(!(foto_mes %in% pmeses),
      get(pcampo),
      tbl$promedio
    )
  ]
}

In [10]:
AsignarNA_campomeses <- function(pcampo, pmeses) {

  if( pcampo %in% colnames( dataset ) ) {

    dataset[ foto_mes %in% pmeses, paste0(pcampo) := NA ]
  }
}

In [11]:

Corregir_atributo <- function(pcampo, pmeses, pmetodo)
{
  # si el campo no existe en el dataset, Afuera !
  if( !(pcampo %in% colnames( dataset )) )
    return( 1 )

  # llamo a la funcion especializada que corresponde
  switch( pmetodo,
    "MachineLearning"     = AsignarNA_campomeses(pcampo, pmeses),
    "EstadisticaClasica"  = Corregir_interpolar(pcampo, pmeses),
    "MICE"                = Corregir_MICE(pcampo, pmeses),
  )

  return( 0 )
}

In [12]:

Corregir_Rotas <- function(dataset, pmetodo) {
  gc(verbose= FALSE)
  cat( "inicio Corregir_Rotas()\n")
  # acomodo los errores del dataset

  Corregir_atributo("active_quarter", c(202006), pmetodo) # 1
  Corregir_atributo("internet", c(202006), pmetodo) # 2

  Corregir_atributo("mrentabilidad", c(201905, 201910, 202006), pmetodo) # 3
  Corregir_atributo("mrentabilidad_annual", c(201905, 201910, 202006), pmetodo) # 4

  Corregir_atributo("mcomisiones", c(201905, 201910, 202006), pmetodo) # 5

  Corregir_atributo("mactivos_margen", c(201905, 201910, 202006), pmetodo) # 6
  Corregir_atributo("mpasivos_margen", c(201905, 201910, 202006), pmetodo) # 7

  Corregir_atributo("mcuentas_saldo", c(202006), pmetodo) # 8

  Corregir_atributo("ctarjeta_debito_transacciones", c(202006), pmetodo) # 9

  Corregir_atributo("mautoservicio", c(202006), pmetodo) # 10

  Corregir_atributo("ctarjeta_visa_transacciones", c(202006), pmetodo) # 11
  Corregir_atributo("mtarjeta_visa_consumo", c(202006), pmetodo) # 12

  Corregir_atributo("ctarjeta_master_transacciones", c(202006), pmetodo) # 13
  Corregir_atributo("mtarjeta_master_consumo", c(202006), pmetodo) # 14

  Corregir_atributo("ctarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 15
  Corregir_atributo("mttarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 16

  Corregir_atributo("ccajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 17

  Corregir_atributo("mcajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 18

  Corregir_atributo("ctarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 19

  Corregir_atributo("mtarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 20

  Corregir_atributo("ctarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 21

  Corregir_atributo("mtarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 22

  Corregir_atributo("ccomisiones_otras", c(201905, 201910, 202006), pmetodo) # 23
  Corregir_atributo("mcomisiones_otras", c(201905, 201910, 202006), pmetodo) # 24

  Corregir_atributo("cextraccion_autoservicio", c(202006), pmetodo) # 25
  Corregir_atributo("mextraccion_autoservicio", c(202006), pmetodo) # 26

  Corregir_atributo("ccheques_depositados", c(202006), pmetodo) # 27
  Corregir_atributo("mcheques_depositados", c(202006), pmetodo) # 28
  Corregir_atributo("ccheques_emitidos", c(202006), pmetodo) # 29
  Corregir_atributo("mcheques_emitidos", c(202006), pmetodo) # 30
  Corregir_atributo("ccheques_depositados_rechazados", c(202006), pmetodo) # 31
  Corregir_atributo("mcheques_depositados_rechazados", c(202006), pmetodo) # 32
  Corregir_atributo("ccheques_emitidos_rechazados", c(202006), pmetodo) # 33
  Corregir_atributo("mcheques_emitidos_rechazados", c(202006), pmetodo) # 34

  Corregir_atributo("tcallcenter", c(202006), pmetodo) # 35
  Corregir_atributo("ccallcenter_transacciones", c(202006), pmetodo) # 36

  Corregir_atributo("thomebanking", c(202006), pmetodo) # 37
  Corregir_atributo("chomebanking_transacciones", c(201910, 202006), pmetodo) # 38

  Corregir_atributo("ccajas_transacciones", c(202006), pmetodo) # 39
  Corregir_atributo("ccajas_consultas", c(202006), pmetodo) # 40

  Corregir_atributo("ccajas_depositos", c(202006, 202105), pmetodo) # 41

  Corregir_atributo("ccajas_extracciones", c(202006), pmetodo) # 41
  Corregir_atributo("ccajas_otras", c(202006), pmetodo) # 43

  Corregir_atributo("catm_trx", c(202006), pmetodo) # 44
  Corregir_atributo("matm", c(202006), pmetodo) # 45
  Corregir_atributo("catm_trx_other", c(202006), pmetodo) # 46
  Corregir_atributo("matm_other", c(202006), pmetodo) # 47

  cat( "fin Corregir_rotas()\n")
}

In [13]:
# resuelvo el Catastrophe Analysis

setorder( dataset, numero_de_cliente, foto_mes )

PARAM$CA$metodo= "MachineLearning"

if( PARAM$CA$metodo %in% c("MachineLearning", "EstadisticaClasica", "MICE") )
  Corregir_Rotas(dataset, PARAM$CA$metodo)

inicio Corregir_Rotas()
fin Corregir_rotas()

#### 9.3.1.3  DR  Data Drifting
Se intenta corregir el data drifting, ajustando por algunos indices financieros

In [14]:
# meses que me interesan para el ajuste de variables monetarias
vfoto_mes <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107, 202108, 202109
)

In [15]:
# los valores que siguen fueron calculados por alumnos

# momento 1.0  31-dic-2020 a las 23:59
vIPC <- c(
  1.9903030878, 1.9174403544, 1.8296186587,
  1.7728862972, 1.7212488323, 1.6776304408,
  1.6431248196, 1.5814483345, 1.4947526791,
  1.4484037589, 1.3913580777, 1.3404220402,
  1.3154288912, 1.2921698342, 1.2472681797,
  1.2300475145, 1.2118694724, 1.1881073259,
  1.1693969743, 1.1375456949, 1.1065619600,
  1.0681100000, 1.0370000000, 1.0000000000,
  0.9680542110, 0.9344152616, 0.8882274350,
  0.8532444140, 0.8251880213, 0.8003763543,
  0.7763107219, 0.7566381305, 0.7289384687
)

vdolar_blue <- c(
   39.045455,  38.402500,  41.639474,
   44.274737,  46.095455,  45.063333,
   43.983333,  54.842857,  61.059524,
   65.545455,  66.750000,  72.368421,
   77.477273,  78.191667,  82.434211,
  101.087500, 126.236842, 125.857143,
  130.782609, 133.400000, 137.954545,
  170.619048, 160.400000, 153.052632,
  157.900000, 149.380952, 143.615385,
  146.250000, 153.550000, 162.000000,
  178.478261, 180.878788, 184.357143
)

vdolar_oficial <- c(
   38.430000,  39.428000,  42.542105,
   44.354211,  46.088636,  44.955000,
   43.751429,  54.650476,  58.790000,
   61.403182,  63.012632,  63.011579,
   62.983636,  63.580556,  65.200000,
   67.872000,  70.047895,  72.520952,
   75.324286,  77.488500,  79.430909,
   83.134762,  85.484737,  88.181667,
   91.474000,  93.997778,  96.635909,
   98.526000,  99.613158, 100.619048,
  101.619048, 102.569048, 103.781818
)

vUVA <- c(
  2.001408838932958,  1.950325472789153,  1.89323032351521,
  1.8247220405493787, 1.746027787673673,  1.6871348409529485,
  1.6361678865622313, 1.5927529755859773, 1.5549162794128493,
  1.4949100586391746, 1.4197729500774545, 1.3678188186372326,
  1.3136508617223726, 1.2690535173062818, 1.2381595983200178,
  1.211656735577568,  1.1770808941405335, 1.1570338657445522,
  1.1388769475653255, 1.1156993751209352, 1.093638313080772,
  1.0657171590878205, 1.0362173587708712, 1.0,
  0.9669867858358365, 0.9323750098728378, 0.8958202912590305,
  0.8631993702994263, 0.8253893405524657, 0.7928918905364516,
  0.7666323845128089, 0.7428976357662823, 0.721615762047849
)

In [16]:
tb_indices <- as.data.table( list(
  "IPC" = vIPC,
  "dolar_blue" = vdolar_blue,
  "dolar_oficial" = vdolar_oficial,
  "UVA" = vUVA
  )
)

tb_indices[[ 'foto_mes' ]] <- vfoto_mes

tb_indices

   IPC       dolar_blue dolar_oficial UVA       foto_mes
1  1.9903031  39.04545   38.43000     2.0014088 201901
2  1.9174404  38.40250   39.42800     1.9503255 201902
3  1.8296187  41.63947   42.54210     1.8932303 201903
4  1.7728863  44.27474   44.35421     1.8247220 201904
5  1.7212488  46.09546   46.08864     1.7460278 201905
6  1.6776304  45.06333   44.95500     1.6871348 201906
7  1.6431248  43.98333   43.75143     1.6361679 201907
8  1.5814483  54.84286   54.65048     1.5927530 201908
9  1.4947527  61.05952   58.79000     1.5549163 201909
10 1.4484038  65.54546   61.40318     1.4949101 201910
11 1.3913581  66.75000   63.01263     1.4197730 201911
12 1.3404220  72.36842   63.01158     1.3678188 201912
13 1.3154289  77.47727   62.98364     1.3136509 202001
14 1.2921698  78.19167   63.58056     1.2690535 202002
15 1.2472682  82.43421   65.20000     1.2381596 202003
16 1.2300475 101.08750   67.87200     1.2116567 202004
17 1.2118695 126.23684   70.04789     1.1770809 202005
18 1.1881073 125.85714   72.52095     1.1570339 202006
19 1.1693970 130.78261   75.32429     1.1388769 202007
20 1.1375457 133.40000   77.48850     1.1156994 202008
21 1.1065620 137.95454   79.43091     1.0936383 202009
22 1.0681100 170.61905   83.13476     1.0657172 202010
23 1.0370000 160.40000   85.48474     1.0362174 202011
24 1.0000000 153.05263   88.18167     1.0000000 202012
25 0.9680542 157.90000   91.47400     0.9669868 202101
26 0.9344153 149.38095   93.99778     0.9323750 202102
27 0.8882274 143.61539   96.63591     0.8958203 202103
28 0.8532444 146.25000   98.52600     0.8631994 202104
29 0.8251880 153.55000   99.61316     0.8253893 202105
30 0.8003764 162.00000  100.61905     0.7928919 202106
31 0.7763107 178.47826  101.61905     0.7666324 202107
32 0.7566381 180.87879  102.56905     0.7428976 202108
33 0.7289385 184.35714  103.78182     0.7216158 202109

In [17]:
drift_UVA <- function(campos_monetarios) {
  cat( "inicio drift_UVA()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.UVA,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_UVA()\n")
}

In [18]:
drift_dolar_oficial <- function(campos_monetarios) {
  cat( "inicio drift_dolar_oficial()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_oficial,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_oficial()\n")
}

In [19]:
drift_dolar_blue <- function(campos_monetarios) {
  cat( "inicio drift_dolar_blue()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_blue,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_blue()\n")
}

In [20]:
drift_deflacion <- function(campos_monetarios) {
  cat( "inicio drift_deflacion()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.IPC,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_deflacion()\n")
}

In [21]:
drift_rank_simple <- function(campos_drift) {

  cat( "inicio drift_rank_simple()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_rank") :=
      (frank(get(campo), ties.method = "random") - 1) / (.N - 1), by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat( "fin drift_rank_simple()\n")
}

In [22]:
# El cero se transforma en cero
# los positivos se rankean por su lado
# los negativos se rankean por su lado

drift_rank_cero_fijo <- function(campos_drift) {

  cat( "inicio drift_rank_cero_fijo()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[get(campo) == 0, paste0(campo, "_rank") := 0]
    dataset[get(campo) > 0, paste0(campo, "_rank") :=
      frank(get(campo), ties.method = "random") / .N, by = list(foto_mes)]

    dataset[get(campo) < 0, paste0(campo, "_rank") :=
      -frank(-get(campo), ties.method = "random") / .N, by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat("\n")
  cat( "fin drift_rank_cero_fijo()\n")
}

In [23]:
drift_estandarizar <- function(campos_drift) {

  cat( "inicio drift_estandarizar()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_normal") :=
      (get(campo) -mean(campo, na.rm=TRUE)) / sd(get(campo), na.rm=TRUE),
      by = list(foto_mes)]

    dataset[, (campo) := NULL]
  }
  cat( "fin drift_estandarizar()\n")
}

In [24]:
# por como armé los nombres de campos,
#  estos son los campos que expresan variables monetarias
campos_monetarios <- colnames(dataset)
campos_monetarios <- campos_monetarios[campos_monetarios %like%
  "^(m|Visa_m|Master_m|vm_m)"]

campos_monetarios

 [1] "mrentabilidad"                      "mrentabilidad_annual"
 [3] "mcomisiones"                        "mactivos_margen"
 [5] "mpasivos_margen"                    "mcuenta_corriente"
 [7] "mcaja_ahorro"                       "mcuentas_saldo"
 [9] "mtarjeta_visa_consumo"              "mtarjeta_master_consumo"
[11] "mprestamos_personales"              "mpayroll"
[13] "mttarjeta_visa_debitos_automaticos" "mcomisiones_mantenimiento"
[15] "mtransferencias_recibidas"          "Master_mfinanciacion_limite"
[17] "Master_msaldototal"                 "Master_mlimitecompra"
[19] "Master_mconsumototal"               "Master_mpagominimo"
[21] "Visa_mfinanciacion_limite"          "Visa_msaldototal"
[23] "Visa_mlimitecompra"                 "Visa_mconsumototal"
[25] "Visa_mpagominimo"

In [25]:
# ejecuto el Data Drifting
setorder( dataset, numero_de_cliente, foto_mes )


PARAM$DR$metodo <- "deflacion"

switch(PARAM$DR$metodo,
  "ninguno"        = cat("No hay correccion del data drifting"),
  "rank_simple"    = drift_rank_simple(campos_monetarios),
  "rank_cero_fijo" = drift_rank_cero_fijo(campos_monetarios),
  "deflacion"      = drift_deflacion(campos_monetarios),
  "dolar_blue"     = drift_dolarblue(campos_monetarios),
  "dolar_oficial"  = drift_dolaroficial(campos_monetarios),
  "UVA"            = drift_UVA(campos_monetarios),
  "estandarizar"   = drift_estandarizar(campos_monetarios)
)

inicio drift_deflacion()
fin drift_deflacion()

In [26]:
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"

#### PCA

In [27]:
# =====================================================================
# EXPERIMENTO V3 - ROTACION PURA (reemplazo, sin truncamiento)
# El modelo entrena SOLO con los ~154 componentes principales.
# Rotacion ortogonal completa: NO se pierde informacion, solo cambia
# la base. Cualquier caida de ganancia vs V0 = sesgo inductivo de
# LightGBM (no invariante a la rotacion) -> Grinsztajn et al. 2022
# =====================================================================

PARAM$PCA <- list()
PARAM$PCA$modo     <- "reemplazo"   # <<< unico cambio conceptual vs V4
PARAM$PCA$varianza <- 1.00          # TODOS los componentes: no se trunca
PARAM$PCA$escalar  <- TRUE          # matriz de correlacion

PARAM$PCA$fit_meses <- c(
  201901:201912, 202001:202012, 202101:202107
)  # solo el pasado: el PCA jamas ve 202109

campos_no_pca <- c("numero_de_cliente", "foto_mes", "clase_ternaria")
campos_pca <- setdiff(colnames(dataset), campos_no_pca)

cat("Atributos originales que entran al PCA:", length(campos_pca), "\n")
stopifnot(length(campos_pca) < 200)   # freno: si hay ~270, se colo FE

# ---- imputacion de NAs (prcomp no los tolera; el CA los genera) ----
# En modo reemplazo imputo IN SITU: las originales se descartan igual.
for (campo in campos_pca) {
  if (anyNA(dataset[[campo]])) {
    dataset[, (campo) := fifelse(is.na(get(campo)),
      as.numeric(median(get(campo), na.rm = TRUE)),
      as.numeric(get(campo))), by = foto_mes]
    dataset[is.na(get(campo)), (campo) := 0]
  }
}

# ---- excluyo columnas de varianza cero en los meses de ajuste ----
m_fit <- as.matrix(dataset[foto_mes %in% PARAM$PCA$fit_meses,
                           campos_pca, with = FALSE])
desvios <- apply(m_fit, 2, sd)
campos_pca <- campos_pca[desvios > 0]
m_fit <- m_fit[, campos_pca]

# ---- ajuste del PCA solo con el pasado ----
pca <- prcomp(m_fit, center = TRUE, scale. = TRUE)
rm(m_fit); gc(verbose = FALSE)

k <- length(pca$sdev)   # TODOS los componentes: rotacion completa
varianza_acum <- cumsum(pca$sdev^2) / sum(pca$sdev^2)
cat("PCA: se retienen", k, "de", length(campos_pca), "variables",
    "( varianza acumulada =", round(varianza_acum[k], 4), ")\n")

# ---- proyecto todo el dataset ----
proyeccion <- predict(pca,
  newdata = as.matrix(dataset[, campos_pca, with = FALSE]))

dataset[, paste0("PC", 1:k) := as.data.table(proyeccion)]
rm(proyeccion); gc(verbose = FALSE)

# ---- REEMPLAZO: elimino los atributos originales ----
dataset[, (campos_pca) := NULL]

PARAM$PCA$componentes_retenidos <- k
cat("Dataset final:", ncol(dataset), "columnas ( solo PC1..PC", k,
    "+ id/foto_mes/clase )\n")

Atributos originales que entran al PCA: 52

Warning message in `[.data.table`(dataset, , `:=`((campo), fifelse(is.na(get(campo)), :
“Group 13 column 'Master_fechaalta': 2267.500000 (type 'double') at RHS position 2 out-of-range(NA) or truncated (precision lost) when assigning to type 'integer' (target vector)”
Warning message in `[.data.table`(dataset, , `:=`((campo), fifelse(is.na(get(campo)), :
“Group 20 column 'Master_fechaalta': 2128.500000 (type 'double') at RHS position 2 out-of-range(NA) or truncated (precision lost) when assigning to type 'integer' (target vector)”
Warning message in `[.data.table`(dataset, , `:=`((campo), fifelse(is.na(get(campo)), :
“Group 8 column 'Visa_fechaalta': 2975.500000 (type 'double') at RHS position 2 out-of-range(NA) or truncated (precision lost) when assigning to type 'integer' (target vector)”
Warning message in `[.data.table`(dataset, , `:=`((campo), fifelse(is.na(get(campo)), :
“Group 23 column 'Visa_fechaalta': 2912.500000 (type 'double') at RHS position 2 out-of-range(NA) or truncated (precision lost) when assigning to type 'integer' (target vector)”

       used      (Mb)  gc trigger (Mb)   max used  (Mb)
Ncells   2156919 115.2   4088732   218.4   3792807  202.6
Vcells 105766923 807.0 312271453  2382.5 318909942 2433.1

PCA: se retienen 52 de 52 variables ( varianza acumulada = 1 )

       used      (Mb)   gc trigger (Mb)   max used  (Mb)
Ncells   2157677  115.3   4088732   218.4   3792807  202.6
Vcells 156568720 1194.6 433815033  3309.8 433064965 3304.1

Dataset final: 55 columnas ( solo PC1..PC 52 + id/foto_mes/clase )

In [28]:
# visualizo las columas del dataset a esta etapa
colnames(dataset)

 [1] "numero_de_cliente" "foto_mes"          "clase_ternaria"
 [4] "PC1"               "PC2"               "PC3"
 [7] "PC4"               "PC5"               "PC6"
[10] "PC7"               "PC8"               "PC9"
[13] "PC10"              "PC11"              "PC12"
[16] "PC13"              "PC14"              "PC15"
[19] "PC16"              "PC17"              "PC18"
[22] "PC19"              "PC20"              "PC21"
[25] "PC22"              "PC23"              "PC24"
[28] "PC25"              "PC26"              "PC27"
[31] "PC28"              "PC29"              "PC30"
[34] "PC31"              "PC32"              "PC33"
[37] "PC34"              "PC35"              "PC36"
[40] "PC37"              "PC38"              "PC39"
[43] "PC40"              "PC41"              "PC42"
[46] "PC43"              "PC44"              "PC45"
[49] "PC46"              "PC47"              "PC48"
[52] "PC49"              "PC50"              "PC51"
[55] "PC52"

### 9.3.2 Modelado

#### 9.3.2.1 Training Strategy

Se hace una estrategia de entrenamiento muy sencilla, tomando todos los meses posibles, SIN eliminar nada x pandemia ni por ningun otro motivo

* future = 202109  obviamente completo

* final_train =  [ 201901, 202107 ]  SIN undersampling

* training
   * testing = NO HAY
   * validation =  202107   completo, sin undersampling
   * training = [ 201901, 202105 ]  donde se consideran el 100% de los CONTINUA

In [29]:
PARAM$trainingstrategy$validate <- c(202107)

PARAM$trainingstrategy$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)


PARAM$trainingstrategy$training_pct <- 1.0


PARAM$trainingstrategy$positivos <- c( "BAJA+1", "BAJA+2")

In [30]:
# seteo la clase01   1={BAJA+1, BAJA+2}   0={CONTINUA}
dataset[, clase01 := ifelse( clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0 )]

In [31]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

In [32]:
# preparo para que se puede hacer undersampling de los CONTINUA
#  solamente por un tema de VELOCIDAD
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset[, azar:=runif(nrow(dataset))]

# undersampling de los CONTINUA
dataset[, fold_train :=  foto_mes %in%  PARAM$trainingstrategy$training &
    (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
     azar < PARAM$trainingstrategy$training_pct ) ]


if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

dtrain <- lgb.Dataset(
  data= data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
  label= dataset[fold_train == TRUE, clase01],
  free_raw_data= TRUE
)

Loading required package: lightgbm

In [33]:
# datos de validation
dvalidate <- lgb.Dataset(
  data= data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
  label= dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
  free_raw_data= TRUE
)

nrow(dvalidate)

[1] 32938

####  9.3.2.2. Hyperparameter Tuning

* Clase binaria que se optimiza :  positivos = [ BAJA+1, BAJA+2 ]

* Metrica que se optimiza **AUC** Area Under Curve de la  ROC Curve

es muy importante notar que intencionalmente  **NO** se está optimizando la funcion de ganancia del problema

* Parametros no default, fijos de LightGBM que no se optimizan
  * max_bin = 31 , Alienigenas Ancestrales contruyeron las pirámides y dejaron a la humanidad en un jeroglifico  *max_bin=31*
  * feature_fraction = 0.5  para poner algo que generalmente no falla
  * learning_rate = 0.03  para que aprenda lento

* Parametros que se optimizan en el Grid Search
  * num_leaves  [64, 512]
  * min_data_in_leaf  [64, 2048]

In [34]:
# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "auc",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  seed= PARAM$semilla_primigenia,
  max_bin= 31,
  learning_rate= 0.03,
  feature_fraction= 0.5,
  num_iterations= 2048,  # valor grande, lo limita early_stopping_rounds
  early_stopping_rounds= 200,
  num_leaves= 64,
  min_data_in_leaf= 128
)

In [35]:
# En  x llegan los parametros moviles de LightGBM
#  devuelve la AUC en validate del modelo entrenado
#  en el parametro x llegan los hiperparámetros que se estan optimizando

Estimar_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM
  modelo_train <- lgb.train(
    data= dtrain,
    valids= list(valid = dvalidate),
    eval= "auc",
    param= param_completo,
    verbose= -100
  )

  # recupero la AUC en validation
  AUC <- modelo_train$record_evals$valid$auc$eval[[modelo_train$best_iter]]

  message(format(Sys.time(), "%a %b %d %X %Y  "),
    toString(x),
    " niter ", modelo_train$best_iter,
    " AUC ", AUC
  )

  # hago espacio en la memoria
  niter <- modelo_train$best_iter
  rm(modelo_train)
  gc(full= TRUE, verbose= FALSE)

  return( list(AUC, niter))
}

seteo del Grid Search

In [36]:
# lo que sigue a continuacion es una forma alternativa a los loops anidados
# creo una tabla con el producto cartesiano de los vectores
tb_nueva <- CJ(
  num_leaves= c(64, 128, 256, 384, 512),
  min_data_in_leaf= c(64, 256, 512, 1024, 2048),
  feature_fraction= c(0.5, 0.8)
)

##### Corrida del Grid Search,  aqui se hace el trabajo pesado
<br> por favor no se asuste con los warnings que pudieran aparecer
<br> ATENCION, la siguiente celda demora 65 minutos
<br> una Analista Jr  debe ser capaz de tolerar estoicamente esta tortura
<br> (y masticar chicle al mismo tiempo)

In [37]:
# registro a registro calculo la AUC
tb_nueva[,  c("AUC", "num_iterations"):= Estimar_AUC_lightgbm( .SD ),
  by=1:nrow(tb_nueva) ]

Sun Jul 12 20:28:40 2026  64, 64, 0.5 niter 793 AUC 0.909145032973935

Sun Jul 12 20:28:59 2026  64, 64, 0.8 niter 435 AUC 0.909110007750487

Sun Jul 12 20:29:23 2026  64, 256, 0.5 niter 466 AUC 0.909364436260438

Sun Jul 12 20:29:41 2026  64, 256, 0.8 niter 379 AUC 0.909885452980554

Sun Jul 12 20:29:56 2026  64, 512, 0.5 niter 269 AUC 0.910231409668759

Sun Jul 12 20:30:16 2026  64, 512, 0.8 niter 449 AUC 0.910683235051235

Sun Jul 12 20:30:33 2026  64, 1024, 0.5 niter 320 AUC 0.911450287444739

Sun Jul 12 20:30:49 2026  64, 1024, 0.8 niter 279 AUC 0.911368804236228

Sun Jul 12 20:31:11 2026  64, 2048, 0.5 niter 459 AUC 0.91187257268593

Sun Jul 12 20:31:28 2026  64, 2048, 0.8 niter 260 AUC 0.91034474600501

Sun Jul 12 20:31:45 2026  128, 64, 0.5 niter 258 AUC 0.907122359362493

Sun Jul 12 20:32:01 2026  128, 64, 0.8 niter 211 AUC 0.907716400369232

Sun Jul 12 20:32:17 2026  128, 256, 0.5 niter 241 AUC 0.910573202981347

Sun Jul 12 20:32:36 2026  128, 256, 0.8 niter 295 AUC 0.909610405848499

Sun Jul 12 20:32:54 2026  128, 512, 0.5 niter 259 AUC 0.910281039749531

Sun Jul 12 20:33:13 2026  128, 512, 0.8 niter 295 AUC 0.911751702622371

Sun Jul 12 20:33:32 2026  128, 1024, 0.5 niter 279 AUC 0.910000044938023

Sun Jul 12 20:33:52 2026  128, 1024, 0.8 niter 287 AUC 0.912031309642008

Sun Jul 12 20:34:16 2026  128, 2048, 0.5 niter 378 AUC 0.911799151887344

Sun Jul 12 20:34:36 2026  128, 2048, 0.8 niter 228 AUC 0.911118935613859

Sun Jul 12 20:34:57 2026  256, 64, 0.5 niter 257 AUC 0.908378311007066

Sun Jul 12 20:35:17 2026  256, 64, 0.8 niter 213 AUC 0.908118133073644

Sun Jul 12 20:35:39 2026  256, 256, 0.5 niter 277 AUC 0.908165978850581

Sun Jul 12 20:36:03 2026  256, 256, 0.8 niter 271 AUC 0.908588462347753

Sun Jul 12 20:36:23 2026  256, 512, 0.5 niter 197 AUC 0.910791614987941

Sun Jul 12 20:36:44 2026  256, 512, 0.8 niter 219 AUC 0.910158451467464

Sun Jul 12 20:37:05 2026  256, 1024, 0.5 niter 203 AUC 0.911997804381087

Sun Jul 12 20:37:26 2026  256, 1024, 0.8 niter 171 AUC 0.910785006455215

Sun Jul 12 20:37:50 2026  256, 2048, 0.5 niter 239 AUC 0.909962838898775

Sun Jul 12 20:38:15 2026  256, 2048, 0.8 niter 194 AUC 0.912811711271619

Sun Jul 12 20:38:48 2026  384, 64, 0.5 niter 426 AUC 0.905238002341007

Sun Jul 12 20:39:16 2026  384, 64, 0.8 niter 267 AUC 0.906065787150263

Sun Jul 12 20:39:38 2026  384, 256, 0.5 niter 183 AUC 0.909022246435886

Sun Jul 12 20:40:02 2026  384, 256, 0.8 niter 161 AUC 0.908377650153794

Sun Jul 12 20:40:26 2026  384, 512, 0.5 niter 210 AUC 0.909082714510329

Sun Jul 12 20:40:50 2026  384, 512, 0.8 niter 158 AUC 0.910419158083504

Sun Jul 12 20:41:15 2026  384, 1024, 0.5 niter 196 AUC 0.910620982672956

Sun Jul 12 20:41:45 2026  384, 1024, 0.8 niter 219 AUC 0.911028530886167

Sun Jul 12 20:42:20 2026  384, 2048, 0.5 niter 386 AUC 0.911051660750708

Sun Jul 12 20:42:48 2026  384, 2048, 0.8 niter 208 AUC 0.911526087315106

Sun Jul 12 20:43:16 2026  512, 64, 0.5 niter 240 AUC 0.905879030015427

Sun Jul 12 20:43:43 2026  512, 64, 0.8 niter 169 AUC 0.906392050410945

Sun Jul 12 20:44:07 2026  512, 256, 0.5 niter 173 AUC 0.907685736777383

Sun Jul 12 20:44:39 2026  512, 256, 0.8 niter 234 AUC 0.907472215085007

Sun Jul 12 20:45:08 2026  512, 512, 0.5 niter 222 AUC 0.90840355560208

Sun Jul 12 20:45:32 2026  512, 512, 0.8 niter 113 AUC 0.908135711770696

Sun Jul 12 20:46:00 2026  512, 1024, 0.5 niter 195 AUC 0.909263788307021

Sun Jul 12 20:46:35 2026  512, 1024, 0.8 niter 226 AUC 0.910133008616469

Sun Jul 12 20:47:09 2026  512, 2048, 0.5 niter 386 AUC 0.911051660750708

Sun Jul 12 20:47:37 2026  512, 2048, 0.8 niter 208 AUC 0.911526087315106

la optimizacion de hiperparámetros de tipo  Grid Search ha corrido, extraigo los mejores hiperparametros

In [38]:
tb_nueva

fwrite( tb_nueva,
  file= "tb_grid_search_01.txt",
  sep="\t",
  append= TRUE
)

   num_leaves min_data_in_leaf feature_fraction AUC       num_iterations
1   64          64             0.5              0.9091450 793
2   64          64             0.8              0.9091100 435
3   64         256             0.5              0.9093644 466
4   64         256             0.8              0.9098855 379
5   64         512             0.5              0.9102314 269
6   64         512             0.8              0.9106832 449
7   64        1024             0.5              0.9114503 320
8   64        1024             0.8              0.9113688 279
9   64        2048             0.5              0.9118726 459
10  64        2048             0.8              0.9103447 260
11 128          64             0.5              0.9071224 258
12 128          64             0.8              0.9077164 211
13 128         256             0.5              0.9105732 241
14 128         256             0.8              0.9096104 295
15 128         512             0.5              0.9102810 259
16 128         512             0.8              0.9117517 295
17 128        1024             0.5              0.9100000 279
18 128        1024             0.8              0.9120313 287
19 128        2048             0.5              0.9117992 378
20 128        2048             0.8              0.9111189 228
21 256          64             0.5              0.9083783 257
22 256          64             0.8              0.9081181 213
23 256         256             0.5              0.9081660 277
24 256         256             0.8              0.9085885 271
25 256         512             0.5              0.9107916 197
26 256         512             0.8              0.9101585 219
27 256        1024             0.5              0.9119978 203
28 256        1024             0.8              0.9107850 171
29 256        2048             0.5              0.9099628 239
30 256        2048             0.8              0.9128117 194
31 384          64             0.5              0.9052380 426
32 384          64             0.8              0.9060658 267
33 384         256             0.5              0.9090222 183
34 384         256             0.8              0.9083777 161
35 384         512             0.5              0.9090827 210
36 384         512             0.8              0.9104192 158
37 384        1024             0.5              0.9106210 196
38 384        1024             0.8              0.9110285 219
39 384        2048             0.5              0.9110517 386
40 384        2048             0.8              0.9115261 208
41 512          64             0.5              0.9058790 240
42 512          64             0.8              0.9063921 169
43 512         256             0.5              0.9076857 173
44 512         256             0.8              0.9074722 234
45 512         512             0.5              0.9084036 222
46 512         512             0.8              0.9081357 113
47 512        1024             0.5              0.9092638 195
48 512        1024             0.8              0.9101330 226
49 512        2048             0.5              0.9110517 386
50 512        2048             0.8              0.9115261 208

In [39]:
setorder( tb_nueva, -AUC)  # ordeno DESCENDENTE por AUC
PARAM$out$lgbm$AUC <- tb_nueva[1, AUC] # en la posicion 1 estan los mejores
PARAM$out$lgbm$mejores_hiperparametros <- as.list( tb_nueva[1] )
PARAM$out$lgbm$mejores_hiperparametros$AUC <- NULL
PARAM$out$lgbm$mejores_hiperparametros

$num_leaves
[1] 256

$min_data_in_leaf
[1] 2048

$feature_fraction
[1] 0.8

$num_iterations
[1] 194

In [40]:
tb_nueva

   num_leaves min_data_in_leaf feature_fraction AUC       num_iterations
1  256        2048             0.8              0.9128117 194
2  128        1024             0.8              0.9120313 287
3  256        1024             0.5              0.9119978 203
4   64        2048             0.5              0.9118726 459
5  128        2048             0.5              0.9117992 378
6  128         512             0.8              0.9117517 295
7  384        2048             0.8              0.9115261 208
8  512        2048             0.8              0.9115261 208
9   64        1024             0.5              0.9114503 320
10  64        1024             0.8              0.9113688 279
11 128        2048             0.8              0.9111189 228
12 384        2048             0.5              0.9110517 386
13 512        2048             0.5              0.9110517 386
14 384        1024             0.8              0.9110285 219
15 256         512             0.5              0.9107916 197
16 256        1024             0.8              0.9107850 171
17  64         512             0.8              0.9106832 449
18 384        1024             0.5              0.9106210 196
19 128         256             0.5              0.9105732 241
20 384         512             0.8              0.9104192 158
21  64        2048             0.8              0.9103447 260
22 128         512             0.5              0.9102810 259
23  64         512             0.5              0.9102314 269
24 256         512             0.8              0.9101585 219
25 512        1024             0.8              0.9101330 226
26 128        1024             0.5              0.9100000 279
27 256        2048             0.5              0.9099628 239
28  64         256             0.8              0.9098855 379
29 128         256             0.8              0.9096104 295
30  64         256             0.5              0.9093644 466
31 512        1024             0.5              0.9092638 195
32  64          64             0.5              0.9091450 793
33  64          64             0.8              0.9091100 435
34 384         512             0.5              0.9090827 210
35 384         256             0.5              0.9090222 183
36 256         256             0.8              0.9085885 271
37 512         512             0.5              0.9084036 222
38 256          64             0.5              0.9083783 257
39 384         256             0.8              0.9083777 161
40 256         256             0.5              0.9081660 277
41 512         512             0.8              0.9081357 113
42 256          64             0.8              0.9081181 213
43 128          64             0.8              0.9077164 211
44 512         256             0.5              0.9076857 173
45 512         256             0.8              0.9074722 234
46 128          64             0.5              0.9071224 258
47 512          64             0.8              0.9063921 169
48 384          64             0.8              0.9060658 267
49 512          64             0.5              0.9058790 240
50 384          64             0.5              0.9052380 426

### 9.3.3 Produccion

#### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

##### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización

In [41]:
PARAM$trainingstrategy$final_train <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107
)


dataset[, fold_final_train := foto_mes %in% PARAM$trainingstrategy$final_train ]

# creo el dfinal_train en formato  LightGBM
dfinal_train <- lgb.Dataset(
  data= data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with= FALSE]),
  label= dataset[fold_final_train == TRUE, clase01],
  free_raw_data= TRUE
)

nrow( dfinal_train) # verifico el tamaño

[1] 910853

##### Final Training Hyperparameters

In [42]:
# uno los parametros fijos y los mejores encontrados de los variables
fijos <- copy(PARAM$lgbm$param_fijos)

# quito lo que optimice en la Bayesian Optimization
fijos$num_iterations <- NULL
fijos$early_stopping_rounds <- NULL

# agrego a los hiperparametros fijos los que encontre con la Bayesian Optimization
param_final <- c(fijos, PARAM$out$lgbm$mejores_hiperparametros)

##### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [43]:
final_model <- lgb.train(
  data= dfinal_train,
  param= param_final,
  verbose= -100
)

In [44]:
# grabo a disco el modelo en un formato para seres humanos ... ponele ...

lgb.save(final_model, "modelo.txt")

In [45]:
# ahora imprimo la importancia de variables

tb_importancia <- as.data.table(lgb.importance(final_model))
archivo_importancia <- "impo.txt"

fwrite( tb_importancia,
  file= archivo_importancia,
  sep= "\t"
)

#### Scoring

Aplico el modelo final a los datos del futuro

In [46]:
PARAM$trainingstrategy$future <- c(202109)

dfuture <- dataset[ foto_mes %in% PARAM$trainingstrategy$future ]

In [47]:
# aplico final_model   a dfuture

prediccion <- predict(
  final_model,
  data.matrix(dfuture[, campos_buenos, with= FALSE])
)

##### Tabla Prediccion

In [48]:
tb_prediccion <- dfuture[, list(numero_de_cliente)]
tb_prediccion[, prob := prediccion]

# grabo las probabilidad del modelo
#  me va a ser util para hacer Ensembles de modelos
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

In [49]:
# ---- ¿Qué componentes usa el modelo? (V3: todo son PCs) ----
tb_imp <- as.data.table(lgb.importance(final_model))
tb_imp[, nro_PC := as.integer(sub("^PC", "", Feature))]

cat("Componentes usados:", nrow(tb_imp), "de", PARAM$PCA$componentes_retenidos, "\n")
cat("Nro de PC mediano (ponderado por Gain):",
    round(sum(tb_imp$nro_PC * tb_imp$Gain) / sum(tb_imp$Gain), 1), "\n\n")

cat("Top 15 componentes:\n")
print(tb_imp[1:15, .(Feature, Gain = round(Gain, 4))])

cat("\n¿Aparece PC21 (el lider en V4)?\n")
print(tb_imp[Feature == "PC21", .(Feature, Gain = round(Gain, 4),
                                  ranking = which(tb_imp$Feature == "PC21"))])

Warning message in eval(jsub, SDenv, parent.frame()):
“NAs introduced by coercion”

Componentes usados: 54 de 52
Nro de PC mediano (ponderado por Gain): NA

Top 15 componentes:
     Feature   Gain
      <char>  <num>
 1:      PC1 0.1410
 2:      PC4 0.1078
 3:      PC6 0.0614
 4:      PC5 0.0523
 5:      PC3 0.0364
 6:     PC28 0.0359
 7: foto_mes 0.0356
 8:      PC2 0.0296
 9:     PC40 0.0231
10:     PC36 0.0212
11:     PC12 0.0205
12:      PC7 0.0197
13:     PC43 0.0197
14:     PC10 0.0195
15:     PC15 0.0193

¿Aparece PC21 (el lider en V4)?
   Feature   Gain ranking
    <char>  <num>   <int>
1:    PC21 0.0098      27

#### Kaggle Competition Submit

Genero las salidas y hago los submits a Kaggle

In [50]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

PARAM$kaggle$competencia <- "data-mining-junior-2026-a"
PARAM$kaggle$cortes <- seq(1800, 2400, by = 100)

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle", showWarnings= FALSE)

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0("./kaggle/KA", PARAM$experimento, "_", envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios,
  "  semilla=", PARAM$semilla_primigenia,
    "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  Sys.sleep(30)
  cat(salida, "\n")
}

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.1), please consider upgrading to the latest version (2.2.2) Successfully submitted to Data Mining, Junior 2026 A

In [51]:
# grabo los parametros
if( !require("yaml")) install.packages("yaml")
require("yaml")

write_yaml( PARAM, file="PARAM.yml")

Loading required package: yaml

In [52]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Jul 12 20:51:31 2026"